### ISSUE TITLE
 Facebook Share SDK (swift) always return 'success' if user cancel the share dailog. Also if user successfully share the 'LInkShareContent' it return empty dictionary.

### ISSUE THREAD

**Issue by smahajan28** [facebook/facebook-swift-sdk#171]
We are using Facebook Share SDK for swift ver 0.2. Whenever we try to share the Link content, we are always getting success in return even if user cancel the operation. Since there are 3 cases: success, cancelled, failed but we are always getting success in this case.
Also if user successfully post the link on his/her wall then we were expecting the post id in the response but again the response is success burt with empty dictionary. We are unable to calculate the number of share user is performing because of the same issue. 

API we are using is listed below:

```swift
let shareContent = LinkShareContent(url: <URL TO SHARE>, title: <TEXT TO SHARE>, description: "", quote: "", imageURL: <IMAGE URL> ?? .none)
do {
  try ShareDialog.show(from: self, content: shareContent, completion: { (result) in
    switch result {
    case .success(let _): // Always getting success with empty dictionary
        completion(true)
    case .cancelled, .failed(_):
        completion(false)
    }
  })
}
catch {
    print("error")
    completion(false)
}
```
We are using iOS version 10.3.2

Facebook SDK version:
0.2

**Comment by f2rozen541** [comment]
I just meet the same issue in Android sdk, can Facebook developers solve the problem?

**Comment by DisappearPing** [comment]
ios 11 sahre always return "cancelled"

**Comment by royherma** [comment]
@DisappearPing 
Try adding this in `AppDelegate`

```
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
SDKApplicationDelegate.shared.application(app, open: url, options: options)
}
```

**Comment by codytwinton** [comment]
@smahajan28 - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by royherma** [comment]
@codytwinton I'm unable to open the issue, but I can attest that there are still issues with this flow.

Specifically, opening the FB share dialog and sharing a post correctly calls the **success** statement on the completion callback, however the "postId" is always nil. 

Furthermore, even if the user doesn't submit the post,  **success** is still returned, making it impossible to validate if a user successfully shared a post.

**Comment by royherma** [comment]
@smahajan28 were you able to solve this?

**Comment by codytwinton** [comment]
@smahajan28 @royherma - good to know. I’ll reopen the issue and use it to track progress.

In the mean time, if anyone finds a solution, feel free to submit a pull request!

**Comment by royherma** [comment]
@codytwinton Do you know if this works for anyone at all on iOS w/ Swift?

**Comment by royherma** [comment]
Also, I am using **Firebase** for my project - perhaps this could be causing issues?

**Comment by codytwinton** [comment]
@royherma - We're in process of resolving the best way to improve this SDK, but I don't believe that Firebase would be conflicting with this SDK. Stay tuned for updates.

In the meantime, if anyone finds a solution, feel free to submit a pull request!

**Comment by royherma** [comment]
Got it - also, here is my code for reference:

```
let myContent = LinkShareContent(url: kFacebookAppShareURL, title: "Cryptonomy", description: nil, quote: "Cryptonomy is an exclusive social network for crypto-enthusiasts where you can track and discuss everything crypto. It's where crypto happens! \n\nI highly recommend it \(kShareHashTag)", imageURL: nil)
        let shareDialog = ShareDialog(content: myContent)
        shareDialog.mode = .automatic
        shareDialog.failsOnInvalidData = true
        shareDialog.completion = { result in
            // Handle share results
            switch result {
            case .success(let response):
                if let postId = response.postId {
                    osPrint("Share succeeded")
                    logEvent(eventName: "User conversion alert action", attributes: ["action": "Succesfully shared to Facebook", "postId": postId])
                    self.giveUserReward()
                } 
                break
            case .failed(let error):
                logEvent(eventName: "User conversion alert action", attributes: ["action": "Failed sharing to Facebook", "error": error.localizedDescription])
                self.showErrorAlert(message: error.localizedDescription)
                break
            case .cancelled:
                logEvent(eventName: "User conversion alert action", attributes: ["action": "Cancelled sharing to Facebook"])
                break
            }
        }
```

**Comment by royherma** [comment]
@codytwinton any update on this? I haven't been able to get any confirmation that this work for anyone, or that your team reproduced it. I have a feature in my app that relies on this flow working correctly (as I imagine many others do), but have yet to get any updates from your team. I wouldn't expect too much but I have always held Facebook to a higher standard! 

Also, let me know if I can help in any way.

Thanks

**Comment by codytwinton** [comment]
@royherma - I apologize for the delay. We'll do our best to get this resolved in the near future.

**Comment by AndrewSB** [comment]
@royherma for now, as a workaround, you could use the Objective-C sharing API instead of the swift one.

**Comment by royherma** [comment]
@AndrewSB Just tried, same issue - submitting a post returns any empty `results` dictionary. Tapping on "Done" without posting (and once logged in with a user) returns the same thing.

Using `FBSDKShareKit (4.21.0)`.

Here is my logic (quite simple):

```
let content = FBSDKShareLinkContent()
        content.contentTitle = "This is a test url"
        content.contentURL = URL(string:"http://google.com")
        FBSDKShareDialog.show(from: self, with: content, delegate: self)
```

Are you able to get different results?

**Comment by royherma** [comment]
This leads me to suspect that something in the url callback / app delegate is incorrect or has been changed, resulting in wrong result values (just a hunch)

**Comment by royherma** [comment]
@codytwinton Done - Hoping for a `swift` solution 🙏 

Thanks for staying in the loop.

**Comment by codytwinton** [comment]
@royherma - Ha!

![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Swift_logo.svg/2000px-Swift_logo.svg.png)

**Comment by Jignesh1805** [comment]
https://github.com/facebook/facebook-sdk-swift/issues/171#issuecomment-408250272

Always return cancelled result can you help me ?

**Comment by royherma** [comment]
The objective-c library actually didn't solve my issue, however after filing a bug on facebook and hearing back, I think the solution is related to making sure the app is question has `user_posts` permission **enabled** (must go through FB auth review...arghhh) @Jignesh1805  @codytwinton

**Comment by Jignesh1805** [comment]
Ok i will try to user_posts permission enabled. 
thank you @royherma

**Comment by Jignesh1805** [comment]
#171 (comment) using this code and return postid nil how to solve this ?
please  help me

**Comment by codytwinton** [comment]
@Jignesh1805 - Thanks for adding this in. I'm going to reopen this issue. I'm actively working on some internal improvements to the underlying iOS SDK, which should offer greater stability for this SDK.

In the meantime, if anyone finds the the solution to this issue, feel free to submit a pull request.

**Comment by Manpreetkaurrao** [comment]
@codytwinton  getting this issue....... as user just clicks done , without sharing the post it gives a callBack to success and in result field, its not returning anything.... please give an ETA for this issue

**Comment by Jignesh1805** [comment]
@royherma 
Can you resolved dictionary empty after uploaded video ?

**Comment by robtimp** [comment]
After changes to the Graph API last year, this is now the expected behavior. No further information is returned on success. We will update the SDK soon to reflect this.

**Comment by Jignesh1805** [comment]
@robtimp How to solved this issue ? Which parameter return in success case ? We have need to postId .
