### ISSUE TITLE
Can't use SDK on iOS Extension

### ISSUE THREAD

**Issue by metpb** [facebook/facebook-swift-sdk#177]
A client app had a share extension with Facebook sharing enabled in it. Previously, we were using the iOS Social Account framework to share images to the users Facebook feed, which has been removed on iOS 11. 

So I tried adding the Facebook SDK to the app extension, but Bolts is throwing an error like this: `'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`

My query is what other ways can I possibly let the user share images from within our app to Facebook (without any server side code). 

Thanks

**Comment by crrobinson14** [comment]
We're having the same problem, which is unfortunate because it's not actually a core SDK issue, it's just Bolts doing something funky with the status bar. For the time being we're routing this stuff server-side.

**Comment by ChandramaniPatel** [comment]
I  have the same issue with MacOS Siera  and Xcode 9.2 .how to resolve this ?

**Comment by mariedm** [comment]
I have the same issue on iOS with an action extension. I can't make it work.

**Comment by yo113** [comment]
Anybody solved it...i am having the same cannot use fb sdk in share extension

**Comment by suroorwijdan** [comment]
Any ongoing efforts to resolve this?

**Comment by yo113** [comment]
You cannot use facebook sdk in share extension. Apple does not allow to use any third party sdk in extension so i also skipped this feature in share extension. Let me know  if in future apple allowed this 
:|

**Comment by suroorwijdan** [comment]
Yes, the SDK uses some unavailable API's on App Extensions, A simple fix would be to use conditional macros in the SDK.

**Comment by codytwinton** [comment]
@metpb We're working on giving this repo some attention. I'll keep you updated here on the progress of this.

Also, if anyone has a fix, feel free to submit a pull request.

**Comment by robtimp** [comment]
Your app extension should communicate with your main app (see https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html), rather than using the SDK directly.

@metpb Please contact [Facebook Developer Support](https://developers.facebook.com/support/) for help with your particular use case.
