### ISSUE TITLE
Can't use with OSX

### ISSUE THREAD

**Issue by dgaedcke** [facebook/facebook-swift-sdk#207]
Has OSX been abandoned or is it supposed to be supported??
I need to auth via Fcbk via a desktop Mac app, and can't find any docs on how best to do this.
Attempting to use this Pod I get:

The platform of the target `FacebookDesktop` (macOS 10.12) is not compatible with `FacebookCore (0.3.0)`, which does not support `osx`.

**Comment by pamontep** [comment]
Did you found any way to do this on desktop Mac app?

**Comment by codytwinton** [comment]
@dgaedcke - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by dgaedcke** [comment]
Cody ... yes, until you guys provide some answer or feedback, it's still an issue for me and for the 5 other people who upvoted.

**Comment by dgaedcke** [comment]
I apologize for being snippy ... I thought you were part of Facebook but now see that you aren't.  Is this supported or not?  And I'm confused as to why a non Fcbk dev team member is responding/closing?

**Comment by dgaedcke** [comment]
it also appears that I'm blocked from re-opening the issue

**Comment by codytwinton** [comment]
@dgaedcke Hey Dewey, yeah I recently joined Facebook. One of my jobs here is to work with this SDK.

I'm really sorry that you've been having issues with this and I'll do what I can to get this resolved asap.

**Comment by robtimp** [comment]
@dgaedcke The Swift and Objective-C SDKs have official support for iOS and tvOS only. For MacOS, please see the [JavaScript SDK](https://developers.facebook.com/docs/facebook-login/web). It’s also possible to [manually build a login flow].(https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow)
