### ISSUE TITLE
LoginManager().logOut() does not actually logout user.

### ISSUE THREAD

**Issue by moger777** [facebook/facebook-swift-sdk#215]
Using LoginManager().logOut() seems to trick UI into think facebook user is logged out but subsequent login attempts don't prompt user for username/password anymore giving user a false sense of security.

**Comment by Quisher** [comment]
how to get the loginmanager object?

**Comment by scottandrew** [comment]
I would like to know about this too. I can not get the user to be forgotten when logged out.

**Comment by Quisher** [comment]
found it out... you can just create a new login manager object and surprisingly calling logout on it results in the original user which logged in using the button also logs out.

**Comment by DavitVosk** [comment]
@Quisher How do you create a new login manager? I am using "react-native-fbsdk" package and there LoginManager.logOut() does not work. Could you please help to solve the problem. Thanks in advance

**Comment by jayson-valentino** [comment]
I have the same issue using Swift SDK. Did someone figure it out? thanks in advance

**Comment by lostatseajoshua** [comment]
Can you all provide more detail on the issue here? What is the desired behavior you are all looking for with the logout method that isn't happening?

**Comment by moger777** [comment]
I'd assume logout would re-prompt user for login/password instead of just retaining login info.

**Comment by jayson-valentino** [comment]
That's what I need as well. Is there anyone have done a workaround so far?

**Comment by skaldic** [comment]
bump

**Comment by LamourBt** [comment]
@skaldic I tried it, still the same thing

**Comment by sachithamadhupa** [comment]
same issue

**Comment by LamourBt** [comment]
@sachithamadhupa  check my update, it would help you

**Comment by codytwinton** [comment]
@moger777 - I'm in process of closing old issues to help us focus on improving this SDK. If you're still running into this issue, please feel free to reopen this issue.

**Comment by moger777** [comment]
Can we re-open? Still having this issue.

**Comment by moger777** [comment]
I can only get logout working for phones with facebook app installed, for those who don't have facebook app, it always caches the last user and logout is useless since they cannot switch users or re-enter password.

**Comment by Quisher** [comment]
@moger777 as mentioned above by me and others.. have you tried making a new instance of login manager and calling logout() from there?
It logs out the main signed in user. Irrespective of whether there is a fb app or not. Otherwise would be interesting to know how your logout flow works.

logically there should be a shared login manager, if every new instance will have the same logged in user. But either way this has worked for us. Please try that.

**Comment by codytwinton** [comment]
Reopening

**Comment by robtimp** [comment]
@intonarumori Thank you for the rundown! 

The new ASWebAuthenticationSession on iOS 12 shares the same behavior as SFSafariViewController (i.e. it’s sandboxed and will thus save cookies even when `logout()` is called)

**Comment by srvkataria** [comment]
You need to **revoke the app permission** on Logout (Before LoginManager.logOut()..)

To revoke the APP permission, you need to send a **GraphRequest** with **accessToken**. Here's how to do it:

customFacebookLogout = () => {
    var current_access_token = '';
    AccessToken.getCurrentAccessToken().then((data) => {
      current_access_token = data.accessToken.toString();
    }).then(() => {
      let logout =
      new GraphRequest(
        "me/permissions/",
        {
            accessToken: current_access_token,
            httpMethod: 'DELETE'
        },
        (error, result) => {
            if (error) {
                console.log('Error fetching data: ' + error.toString());
            } else {
                LoginManager.logOut();
            }
        });
      new GraphRequestManager().addRequest(logout).start();
    })
    .catch(error => {
      console.log(error)
    });      
  }

**Comment by syedtehrimabbas** [comment]
@srvkataria Great Job now It log out but not prompting the user to re-enter login details but it asked for the user to login as "Username".
but It's really great.

**Comment by klauslanza** [comment]
The new SDK now has only one behavior 

`loginManager.loginBehavior = .browser`

and it's not working anymore for @intonarumori suggested workaround.

Any idea?
Thanks

**Comment by thangbomvn** [comment]
I have the same issue with @klauslanza. I have only one way, open safari browser then logout facebook, remove account from browser by manual. I'm using FBSDK 4.44.0
Please help me.
Thanks

**Comment by codytwinton** [comment]
@robtimp - Can you share any thoughts on this?

**Comment by robtimp** [comment]
@klauslanza @thangbomvn `loginManager.logOut()` is only intended to log the user out of your app, but does not log the user out of Facebook in Safari.

If you would like to display the permissions dialog rather than the 'Continue As' screen, call DELETE on the `me/permissions` endpoint, as @srvkataria has shown above.

**Comment by thangbomvn** [comment]
Sorry, i want to show login screen ( enter email, password) to login with other facebook account. I need  login with more than one facebook account. 
Is there any way ? 
Thank you

**Comment by thangbomvn** [comment]
@intonarumori : Can you share me your version of FBSDK you used ? I use the newest version of FBSDK for ios,  Web behavior is deprecated.

**Comment by demetriusatbenchprep** [comment]
Since Safari's cookies are sandboxes, you'd think Facebook would invalidate the user's cookie/token associated with the app - forcing the user re-enter their password. This is a bad UX and big security concern - at the very least during development when testing multiple accounts and QA testing on multiple devices.

**Comment by mdaniyalaslam** [comment]
I

> You need to **revoke the app permission** on Logout (Before LoginManager.logOut()..)
> 
> To revoke the APP permission, you need to send a **GraphRequest** with **accessToken**. Here's how to do it:
> 
> ```
> customFacebookLogout = () => {
>     var current_access_token = '';
>     AccessToken.getCurrentAccessToken().then((data) => {
>       current_access_token = data.accessToken.toString();
>     }).then(() => {
>       let logout =
>       new GraphRequest(
>         "me/permissions/",
>         {
>             accessToken: current_access_token,
>             httpMethod: 'DELETE'
>         },
>         (error, result) => {
>             if (error) {
>                 console.log('Error fetching data: ' + error.toString());
>             } else {
>                 LoginManager.logOut();
>             }
>         });
>       new GraphRequestManager().addRequest(logout).start();
>     })
>     .catch(error => {
>       console.log(error)
>     });      
>   }
> ```

I tried like this : 

`let logout = new GraphRequest(
      "/me/permissions/",
      {
        httpMethod: 'DELETE',
    },
      (error, result) => {
        console.log(result);
          if (error) {
              console.log('Error fetching data: ' + error.toString());
          } else {
              LoginManager.logOut();
              this.props.navigation.navigate('Login');
          }
      });
     new GraphRequestManager().addRequest(logout).start(); `

**Comment by mdaniyalaslam** [comment]
/// try this : 
let logout = new GraphRequest(
      "/me/permissions/",
      {
        httpMethod: 'DELETE',
    },
      (error, result) => {
        console.log(result);
          if (error) {
              console.log('Error fetching data: ' + error.toString());
          } else {
              LoginManager.logOut();
              this.props.navigation.navigate('Login');
          }
      });
     new GraphRequestManager().addRequest(logout).start();

**Comment by DenisSemerych** [comment]
Do any one have ideas about log out with swift FBSDK last version? Have the same issue and for app purposes it is not good to make some extra requests to FB. Maybe there is some way in provided SDK by Facebook? 
Thank in advance!
