### ISSUE TITLE
Facebook ShareDialog crashes with EXC_BAD_ACCESS if Facebook app is not installed (iOS 11.3 XCode 9.3)

### ISSUE THREAD

**Issue by mkeremkeskin** [facebook/facebook-swift-sdk#227]
If Facebook App is installed share process is done successfully, but if Facebook app is not installed Facebook SDK throws `EXC_BAD_ACESS`. You can see the screen where it crashed. Crash occurs in **SDKSharingDelegateBridge.swift** class.

![fb crash](https://user-images.githubusercontent.com/4717926/39868870-2411ec54-5464-11e8-958f-f4a7261ea964.png)

If app not installed it should supposed to open WebView or give some error. It shouldn't crash and give me no error.

Since there is no log for the crash I only have **EXC_BAD_ACCESS**.

My environment:

XCode 9.3
Swift 3.3
iOS 11.3
FacebookShare (0.3.0) (from CocoaPods)

Have anyone came across to this situation? Thx already.

Below is the code snippet from the app which is copied from the offical docs. (https://developers.facebook.com/docs/swift/sharing/share-dialog)

```
var shareContent: LinkShareContent?

if let urlstring = urlStr, let url = URL(string: urlstring) {
    shareContent = LinkShareContent(url: url, quote: initialText)
}

let shareDialog = ShareDialog(content: shareContent!)
shareDialog.mode = .native
shareDialog.failsOnInvalidData = true
shareDialog.completion = { result in
    // Handle share results
}

do {
    try shareDialog.show()
}
catch {

}
```

You can see my stackoverflow thread here:
https://stackoverflow.com/questions/50272500/facebook-sharedialog-crashes-with-exc-bad-access-if-facebook-app-is-not-installe/50274158#50274158

**Comment by AndrewSB** [comment]
Yeah, that looks like a pretty legitimate failure. `EXC_BAD_ACCESS` is sometimes a synonym for force unwrapping something.
I'll throw up a change that I think might fix it on a branch.

**Comment by AndrewSB** [comment]
@mkeremkeskin I'm less sure now - since `Error` can be implicitly converted to `NSError`. I made the change I was thinking of anyway though, over here: https://github.com/facebook/facebook-sdk-swift/tree/fix-non-fb-crash. Let me know if that fixes the issue for you? If not, we can look further

**Comment by mkeremkeskin** [comment]
@AndrewSB thanks Andrew. I will try it when I'm available and let you know. 

Also you can see my temporary solution below. By this way I can eliminate crash on case Facebook app is not installed.

```
if  UIApplication.shared.canOpenURL(URL(string: "fb://")!){
    shareDialog.mode = .native
}
else {
    shareDialog.mode = .automatic
}
```

**Comment by adeline-t** [comment]
@AndrewSB : I have the same issue.
I've tried your fix with no success

Objective-C code return a nil error which generate the swift crash.

I add 2 screenshot.
With my stack Was able to go to the objective-C code and as you can see error is nil
Add in Swift code, you have a raw pointer for error. 

![capture d ecran 2018-05-31 a 17 34 03](https://user-images.githubusercontent.com/4289525/40792232-c45aab6a-64f9-11e8-9cfc-e6ca7ac5fb86.png)
![capture d ecran 2018-05-31 a 17 33 26](https://user-images.githubusercontent.com/4289525/40792233-c477b00c-64f9-11e8-886d-b0aa8c156c55.png)


Thanks for your help

**Comment by littleylv** [comment]
@AndrewSB  It does not work.

**Comment by AndrewSB** [comment]
That stack trace was really helpful @adeline-t, it looks like objective-C can pass in a non-null NSError, and because SDKSharingDelegateBridge isn't type safe, we aren't handling that.
I've attempted a fix in https://github.com/facebook/facebook-sdk-swift/tree/maybe-fix-bridging-crash, do you want to see if that works for you?

**Comment by adeline-t** [comment]
@AndrewSB Sorry doesn't work

i made quick fix :
`    if let nsError = error as? NSError, let failedError = ShareError(error:nsError) {
        completion?(.failed(failedError))
    } else if let er = error as? Error{
        completion?(.failed(er))
    }
    else {
        completion?(.failed(ShareError.unknown))
    }`

Sorry i don't have time to do a proper pull request

**Comment by robtimp** [comment]
@mkeremkeskin This crash is now fixed on the master branch of `facebook-objc-sdk`, and will return the correct error, rather than the unexpected nil. Please update to the `master` branch, or version `4.40.0` when it’s released next week.

**Comment by houmie** [comment]
Is there any ETA when this will be updated on Cocoapods? Thanks
