### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by shawnwall** [facebook/facebook-swift-sdk#228]
Given the podspec hasn't been updated in 7 months, I don't see a clear way to update the changed objective-c dependencies via cocoapods. Can you keep the podspec updated to reference the newer versions of the dependencies, or document how to keep them updated?

**Comment by codytwinton** [comment]
@shawnwall - We're working to give this repo some love. I'll keep you updated here on the progress.

**Comment by robtimp** [comment]
The `podspec` has just been updated
