### ISSUE TITLE
publish_actions permission not granted

### ISSUE THREAD

**Issue by crickabhi** [facebook/facebook-swift-sdk#234]
I am asking for publish_actions permission but i am not able to get those permissions.
![img_7980](https://user-images.githubusercontent.com/10657329/40900840-35389f56-67eb-11e8-8c3a-7a9fd6e7594c.JPG)

**Comment by animis93** [comment]
I have same problem with this error: 
"FBSDKLog: Warning: Access token is missing publish_actions permission"
Someone has solved this problem?

**Comment by SunXiaoShan** [comment]
I get the same problem with this error:
FBSDKLog: Warning: Access token is missing publish_actions permissions

`        let loginButton : FBSDKLoginButton = FBSDKLoginButton()
        loginButton.frame = CGRect( x: 20, y: 200, width: self.view.frame.size.width - 40, height: 50)
        loginButton.readPermissions = ["public_profile", "email", "publish_actions"]
        loginButton.publishPermissions = ["publish_actions"]
        loginButton.delegate = self
        self.view.addSubview(loginButton)`

**Comment by codytwinton** [comment]
We're working on giving this repo some attention. I'll keep you updated here on the progress of this bug.

Also, if anyone has a fix, feel free to submit a pull request.

**Comment by dkpachiappan** [comment]
We already implemented sharing code on facebook by programmatically using publish_action permission. Now, what will happen after 1 August 2018? 

And what is the alternate way to share image/video on facebook by programmatically without share dialog?

**Comment by codytwinton** [comment]
I'll work on getting you answers as soon as possible.

**Comment by Jignesh1805** [comment]
hi codytwinton
can solved And what is the alternate way to share image/video on facebook by programmatically without share dialog?

**Comment by probitaille** [comment]
Since August 1st, 2018, the Live API publish_actions permission, which allows an app to publish on behalf of its Users, will be reserved for approved partners.

**Comment by robtimp** [comment]
From https://developers.facebook.com/docs/graph-api/changelog/breaking-changes:

`The publish_actions permission has been removed. Apps that have already been approved for publish_actions can continue using the permission until August 1st, 2018. If you want to provide a way for your app users to share content to Facebook and Instagram beyond this date, we encourage you to use our Sharing products instead.`

**Comment by JustinJusz** [comment]
> I am asking for publish_actions permission but i am not able to get those permissions.
> ![img_7980](https://user-images.githubusercontent.com/10657329/40900840-35389f56-67eb-11e8-8c3a-7a9fd6e7594c.JPG)

Did you solve this issue.?

**Comment by robtimp** [comment]
@JustinJusz The `publish_actions` permission is no longer supported

**Comment by JustinJusz** [comment]
> @JustinJusz The `publish_actions` permission is no longer supported

Then how I integrate facebook sharing without using "publish_actions" permission..? Is there any other way ?

**Comment by robtimp** [comment]
@JustinJusz No special permissions should be needed to use the Share Dialog or Share Extension. Read more here: https://developers.facebook.com/docs/sharing/ios
