### ISSUE TITLE
FBSDKShareLinkContent & Emoji

### ISSUE THREAD

**Issue by Sunrizzin** [facebook/facebook-swift-sdk#240]
Hello! Use:

```swift
let content = FBSDKShareLinkContent()
content.contentURL = URL(string: urlToShare)
content.quote = "Hello!😃 Good luck! 😊"
FBSDKShareDialog.show(from: self, with: content, delegate: nil)
```

and result:

<img width="575" alt="2018-06-17 20 44 01" src="https://user-images.githubusercontent.com/16189633/41507954-42c2a94e-726f-11e8-8f1a-758c1f99c2db.png">

Why don't show emoji?

```
- FacebookShare (0.3.1):
    - Bolts (~> 1.8)
    - FacebookCore (~> 0.3.1)
    - FBSDKCoreKit (~> 4.33)
    - FBSDKShareKit (~> 4.33)
```

**Comment by codytwinton** [comment]
I'll do my best to look into this asap.

**Comment by robtimp** [comment]
@Sunrizzin It was necessary to make a change on the web side of things, but emoji should now display properly when included in the 'quote' of a share.
