### ISSUE TITLE
Facebook link sharing is not working

### ISSUE THREAD

**Issue by shkar62** [facebook/facebook-swift-sdk#242]
I am working on Facebook link sharing in iOS.

```swift
let content = FBSDKShareLinkContent()
let contentUrl = "https://developers.facebook.com"
content.contentURL = URL(string: contentUrl)

let dialog = FBSDKShareDialog()
dialog.mode = FBSDKShareDialogMode.automatic
dialog.shareContent = content
dialog.delegate = self as FBSDKSharingDelegate
dialog.fromViewController = self
dialog.show
```

This is my code. When I click on Post button in the share dialog, I always get error: `There was some problem in sharing the link`.

Can somebody assist?

**Comment by codytwinton** [comment]
@shkar62 - Have you tried this:

```swift
let content = FBSDKShareLinkContent()
content.contentURL = URL(string: "https://developers.facebook.com")

let dialog = FBSDKShareDialog()
dialog.mode = .automatic
dialog.show(from: self, with: content, delegate: self)
```

**Comment by robtimp** [comment]
@shkar62 Looks like we'll need to know more about your specific app to be able to assist. Please contact [Facebook Developer Support](https://developers.facebook.com/support) for assistance.

**Comment by JokerApp** [comment]
@robtimp @codytwinton  I'm working on Facebook sharing too and have the same issue with @shkar62.
`let shareContent = FBSDKShareLinkContent()
  shareContent.contentURL = link
  FBSDKShareDialog.show(from: Shared.topVc(), with: shareContent, delegate: self)`

I'm trying to share simple link (also tried to share https://developers.facebook.com and it doesn't work).

**Comment by shkar62** [comment]
@JokerApp I was able to get the issue resolved. You need to use the developer facebook account for testing purpose while logging to facebook app. I was using different accounts and hence was getting issues. Also I modified the code a bit: 
`DispatchQueue.main.async {
            let dialog = FBSDKShareDialog()
            dialog.fromViewController = self
            dialog.shareContent = content
            dialog.mode = FBSDKShareDialogMode.native
            dialog.show()
        }`

**Comment by JordanPJamieson** [comment]
> @robtimp @codytwinton I'm working on Facebook sharing too and have the same issue with @shkar62.
> `let shareContent = FBSDKShareLinkContent()`
> `shareContent.contentURL = link`
> `FBSDKShareDialog.show(from: Shared.topVc(), with: shareContent, delegate: self)`
> 
> I'm trying to share simple link, it doesn't work and can't post this link and text to the news feed (also tried to share https://developers.facebook.com and it doesn't work too). But, it can post the same link and text to the user's story.
> 
> Also, I was able to share link to my friend in Facebook. But still cannot share it to news feed

I'm having the same issue as you, I can share to a story but not the news feed.  Did you resolve this issue? Thank you! @JokerApp
