### ISSUE TITLE
Not able to fetch user's gender and cover image in graph API Swift

### ISSUE THREAD

**Issue by vinayakpal** [facebook/facebook-swift-sdk#278]
I recently Updated my FBSDK pod to 4.36.0 . And realised during login user's gender and cover image not return by the graph API. before that I was working perfectly fine but for now user's gender and cover image value returns nil. Kindly help to sort this issue

**Comment by vinayakpal** [comment]
@otymartin by adding `user_gender` throws exception during facebook login

**Comment by vinayakpal** [comment]
@7Dman  `["fields":"id,name,first_name,last_name,gender,email,birthday,picture.type(large),cover"]`
those are the parameters i applied while using graph API

**Comment by otymartin** [comment]
@vinayakpal Those are the fields params not the `permissions` params. `user_gender` goes in the `Permissions` parameter of the Graph Request

**Comment by robtimp** [comment]
@vinayakpal If you're still experiencing this issue, please contact Facebook developer support here: https://developers.facebook.com/support/

They can help ensure all necessary permissions are correctly configured for your account and app.
