### ISSUE TITLE
Error whe using CocoaPods

### ISSUE THREAD

**Issue by ilbordi** [facebook/facebook-swift-sdk#280]
Hi, I have a problem when installing FacebookShare with CocoaPods, Xcode gives me the following error: clang: error: linker command failed with exit code 1 (use -v to see invocation)
How can I fix?

## Environment

- Xcode Version: `10.0`
- Swift Version: `4.2`
- Installation Platform & Verison: Cocoapods

**Comment by lostatseajoshua** [comment]
Can you add more description of the error? In Xcode navigate to the issue navigator and click on the error to get more information.
Have you tried reinstalling Cocoapod frameworks?
Have you tried cleaning the build folder and derived data?

**Comment by ilbordi** [comment]
Hi, I have already cleaned the project and deriver data.
Here's the error:
<img width="1015" alt="schermata 2018-10-11 alle 13 51 40" src="https://user-images.githubusercontent.com/13150194/46802196-f40d5580-cd5c-11e8-9798-ce5af8dc2675.png">

Here's my pod file:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hotel' do
  use_frameworks!
project ".../Hotel.xcodeproj"

  # Pods for Hotel
pod 'Kingfisher', '~> 4.0'
pod "FacebookShare"

  target 'HotelTests' do
    inherit! :search_paths
    # Pods for testing
 end

  target 'HotelUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

**Comment by nft2** [comment]
See https://stackoverflow.com/a/18618187/9482608

**Comment by robtimp** [comment]
Closing as this issue seems to pertain more to Cocoapods than the SDK itself. Please see https://github.com/CocoaPods/CocoaPods/issues for support.
