### ISSUE TITLE
Carthage update failed

### ISSUE THREAD

**Issue by TonyPNguyen** [facebook/facebook-swift-sdk#292]
I ran with the command

> carthage update --platform iOS --no-use-binaries

and the link i used is
> github "facebook/facebook-sdk-swift" ~> 0.5.0

This is the error i get below

> *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Bolts-iOS" in Bolts.xcodeproj
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKCoreKit-Universal" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKPlacesKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKShareKit-Dynamic" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/tonynguyen/Desktop/Gym\ Ting/Carthage/Checkouts/facebook-objc-sdk/FacebookSDK.xcworkspace -scheme FBSDKShareKit-Dynamic -configuration Release -derivedDataPath /Users/tonynguyen/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/facebook-objc-sdk/6336145d334ed4e9e7174ebbfbd2d0b82e48393c -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/k3/py3lhnrn0r9b4wdt2q9pl4vh0000gn/T/facebook-objc-sdk SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/tonynguyen/Desktop/Gym Ting/Carthage/Checkouts/facebook-objc-sdk)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/k3/py3lhnrn0r9b4wdt2q9pl4vh0000gn/T/carthage-xcodebuild.pPj3gS.log

**Comment by danmolina21** [comment]
I am having the exact same issue.

**Comment by txaiwieser** [comment]
The only thing I'm always 100% sure its that the facebook sdk will fail to compile when I tried to update.

**Comment by walsht** [comment]
Can we get some support on this?  I basically can't build facebook via Carthage 

```In module 'FBSDKCoreKit' imported from /Users/tim/Git/app-cnet/Carthage/Checkouts/facebook-objc-sdk/FBSDKShareKit/FBSDKShareKit/FBSDKShareAPI.h:21:
/Users/tim/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/facebook-objc-sdk/6336145d334ed4e9e7174ebbfbd2d0b82e48393c/Build/Intermediates.noindex/ArchiveIntermediates/FBSDKShareKit_TV-Dynamic/BuildProductsPath/Release-appletvos/FBSDKCoreKit.framework/Headers/FBSDKGraphRequestConnection.h:230:1: note: 'addRequest:completionHandler:batchEntryName:' has been explicitly marked deprecated here```

I have tried almost everything and nothing is building.  I am stuck now.
1. github “facebook/facebook-swift-sdk” “master”
2. github “facebook/facebook-swift-sdk” “0.5.0"
3. github “facebook/facebook-swift-sdk” “0.4.0"
4. This just loops on carthage update...
github “facebook/facebook-objc-sdk” “6336145d334ed4e9e7174ebbfbd2d0b82e48393c”
github “facebook/facebook-swift-sdk” “0.5.0"

**Comment by aechap02** [comment]
As a workaround for now you can use my fork: `github "aechap02/facebook-swift-sdk"`

The only thing I changed is their Cartfile. Updated it to use the latest tagged facebook-objc-sdk version, instead of the master branch.

**Comment by txaiwieser** [comment]
Still not fixed

**Comment by aechap02** [comment]
My fork doesn’t work for you? Same exact issue, or something else? Cartfile.resolved should show 0.5.01 for facebook-swift-sdk and sdk-version-4.38.1 for facebook-obj-sdk.. those two versions are building fine for me. Also make sure Carthage is up to date, 0.31.2.

**Comment by vol24pl** [comment]
+1 for fixing this.

It'd be great to be able to have this fix when updating Carthage, without any fuss:
https://github.com/facebook/facebook-objc-sdk/pull/922

**Comment by mmdumi** [comment]
This is still not fixed. +1

**Comment by lostatseajoshua** [comment]
#316 Sets carthage to use semantic version so it will be stable. It has been merged please try updating again. If it persists please reopen this issue.
