### ISSUE TITLE
FacebookSDK Share Video content is not working

### ISSUE THREAD

**Issue by kirankumarg99** [facebook/facebook-swift-sdk#296]
# Facebook Swift SDK Issue

## Checklist

FacebookSDK Share Video content is not working . Please help me in resolving the issue.
I am trying to post a video from my application bundle to Facebook.
## Code:

 let content: FBSDKShareVideoContent = FBSDKShareVideoContent()
        let videoURL = Bundle.main.url(forResource: "ImageSlideShow", withExtension: "mp4")!
            let video = FBSDKShareVideo()
            video.videoURL =  videoURL
            content.video = video        
                content.contentURL = NSURL(string: "http://www.demo.com")! as URL        
                FBSDKShareDialog.show(from: self, with: content, delegate: self as FBSDKSharingDelegate)

## Error received:
The operation couldn’t be completed. (com.facebook.sdk.share error 2.)

**Comment by RayTouch** [comment]
+1

**Comment by robtimp** [comment]
@kirankumarg99 @RayTouch 

Setting the `videoURL` property will not work with a video contained inside an app, only for videos on the web.

For this case, you’ll need to create a `Data` object from your video to share:

```
let videoURL = Bundle.main.url(forResource: "ImageSlideShow", withExtension: "mp4")!
let video = FBSDKShareVideo()
video.data = try! Data(contentsOf: videoURL)
```

Note that `try!` should be acceptable in this instance since the resource is contained within your app. It should always succeed as long as the video URL is correct.

**Comment by Neelu1112** [comment]
it's not working for me, am getting below error
Share error: The operation couldn’t be completed. (com.facebook.sdk.share error 2.)

> @kirankumarg99 @RayTouch
> 
> Setting the `videoURL` property will not work with a video contained inside an app, only for videos on the web.
> 
> For this case, you’ll need to create a `Data` object from your video to share:
> 
> ```
> let videoURL = Bundle.main.url(forResource: "ImageSlideShow", withExtension: "mp4")!
> let video = FBSDKShareVideo()
> video.data = try! Data(contentsOf: videoURL)
> ```
> Note that `try!` should be acceptable in this instance since the resource is contained within your app. It should always succeed as long as the video URL is correct.

not working for me

**Comment by VittoriDavide** [comment]
+1

**Comment by dawilliams-gpsw** [comment]
+1, 

We see the same issue.`com.facebook.sdk.share error 2`, although the data can be played in quicktime, and even uploaded directly to facebook over the web.
