### ISSUE TITLE
Facebook Login failed on ios (com.facebook.sdk.login error 308.) Enabling Keychain access does not work. Any solution? 

### ISSUE THREAD

**Issue by PurushottamPadhya** [facebook/facebook-swift-sdk#306]

**Comment by gakuzzz** [comment]
me too

**Comment by prundianudaniel** [comment]
thanks for the nice description :)

**Comment by robtimp** [comment]
This issue should now be fixed on the master branch of `facebook-objc-sdk`, but there is not yet a release version of the fix (though we’re hoping to have one out ASAP). 

In the meantime, please use this workaround:

Add 
`pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'`
to your podfile.

**Comment by xuaimian** [comment]
> This issue should now be fixed on the master branch of `facebook-objc-sdk`, but there is not yet a release version of the fix (though we’re hoping to have one out ASAP).
> 
> In the meantime, please use this workaround:
> 
> Add
> `pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'`
> to your podfile.

Hi，Robtimp,
I used above link, but it caused below issue,
loginButtonDidCompleteLoginError:Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}
thanks in advance!

**Comment by robtimp** [comment]
@xuaimian Please see https://github.com/facebook/facebook-swift-sdk/issues/301 for a workaround

**Comment by soheilnikbin** [comment]
We still getting this error on the latest version of the Facebook SDK, below is the pod configuration:
   ```
    pod 'FBSDKCoreKit'
    pod 'FacebookCore' , '~> 0.5.0'
    pod 'FacebookLogin', '~> 0.5.0'
    pod 'FacebookShare', '~> 0.5.0' 
```
when I'm using your solution from master, getting around 48 error from the lib, because its not compatible with Swift 4.2.

Any Suggestion?!  this issue is live on our production app.

**Comment by xuaimian** [comment]
pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
  pod 'FacebookCore'
  pod 'FacebookLogin'
Run `pod deintegrate`, then `pod install`.
 try this solution.

**Comment by robtimp** [comment]
@soheilnikbin Which version of the SDK are you currently using? This should be fixed on 4.40.0, so the comments to temporarily use the `master` branch should no longer apply

**Comment by soheilnikbin** [comment]
@robtimp By saying 4.40.0 do you mean ( 0.4.0), because in the release section this is what I found and I'm using 0.5.0 which is newer than 0.4.0. 
The error is :
`com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.`

**Comment by robtimp** [comment]
@soheilnikbin I’m referring to the version of the underlying Objective-C SDK, which was the source of the issue. Check your podfile.lock to see which versions your app is using. The latest is 4.40.0

You may need to run `pod update FBSDKCoreKit`. Also `pod update FBSDKLoginKit` and `pod update FBSDKShareKit` if you’re using the login or sharing functionality.

**Comment by robtimp** [comment]
You should be able to move back to 0.5.0 and keep the 4.40.0 version of the ObjC SDK.

While the Swift SDK is in beta, it just uses the latest Objective-C SDK release for its dependencies by default

**Comment by soheilnikbin** [comment]
@robtimp Thanks start working now, ` pod update FBSDKCoreKit` did the trick.
