### ISSUE TITLE
 when I click to login, and there was no response.

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [facebook/facebook-swift-sdk#307]
## Checklist

when I click to login, and there was no response.

-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.}

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: Version 10.1 (10B61)
- Swift Version: 4.1
- Installation Platform & Verison: `[Cocoapods|Carthage|Manual]` version  updated Version 
4.39.0 - FBSDKLoginKit 
FBSDKCoreKit - 4.39.0

## Expected Results
not able to open facebook url 

## Actual Results

Error Domain=com.facebook.sdk.core Code=3 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Unknown error building URL.

It is to note previously this was working but now this get stop working

**Comment by atif-khan** [comment]
I am also facing the issue. I always get 'isCanceled = true' after login from the native Facebook app but works fine when I choose email/mobile no. option.

**Comment by robtimp** [comment]
@SURYAKANTSHARMA @atif-khan I believe you're seeing the same issue as #298 and #301. I also posted this workaround there:

Please add pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master' to your podfile. Run `pod deintegrate`, then `pod install`.

**Comment by atif-khan** [comment]
@robtimp thank you for the workaround. It worked for all devices except iPhone 6 Plus. 
I always get "result?.isCancelled == true" in iPhone 6 plus. 
Please help.

**Comment by atif-khan** [comment]
@robtimp thank you for the solution. It worked in most of the iPhone models but the issue still exists in **Plus devices**. I am testing in **iPhone 6 Plus** and I am getting the same issue. 
Please help.

**Comment by YousefAlsbaihi** [comment]
had same problem, do this [H E R E](https://github.com/facebook/facebook-swift-sdk/issues/298#issuecomment-449626683) Worked for me after hours and hours of struggling.

**Comment by YousefAlsbaihi** [comment]
> @robtimp Thanks for suggestion. But it don't work for me even after pod deintegrate, then pod install .
> pod 'FBSDKLoginKit', '~> 4.38.0'

do this 

Solved for me :

Delete Podfile.lock
Delete Pods folder
replace the facebook pods in your Podfile with this version of facebook
```
pod 'FBSDKCoreKit', '~> 4.38.0'
pod 'FBSDKLoginKit', '~> 4.38.0'
```
now please notice that if you have FacebookShareKit or anything else for facebook you have to change it to the same version you are using which is 4.38.0

run your terminal with pod install
open your project, go to Product > Clean Build Folder
run the app and try.

worked for me, if it does for you let everybody knows.

**Comment by SURYAKANTSHARMA** [comment]
@YousefAlsbaihi Thanks for your reply but now it worked when 
 pod 'FBSDKCoreKit', '~> 4.38.0' 
 pod 'FBSDKLoginKit', '~> 4.38.0'
 Install both 

 earlier i had install pod 'FBSDKLoginKit', '~> 4.38.0'  only. 
At last thanks 👍 @YousefAlsbaihi  @robtimp  for help me for tackling the same
