### ISSUE TITLE
Facebook custom events not work

### ISSUE THREAD

**Issue by SerhiiMatvieiev** [facebook/facebook-swift-sdk#310]
I use FacebookCore to log custom events, but there is no any custom events at Analytics dashboard. 

I activated my app for analytics like this:

func applicationDidBecomeActive(application: UIApplication) {
    AppEventsLogger.activate(application)
}

And send custom event (fake data):

let name = "some_event_name"
let metadata = ["some_key": "some_value"]
var params: [AppEventParameterName: String] = [:]
    metadata.forEach {
      params[AppEventParameterName.custom($0)] = $1
    }
    let event = AppEvent(name: name, parameters: params)
    AppEventsLogger.log(event)

In debug console (real data) :

FBSDKLog: FBSDKAppEvents: Recording event @ 1545987980: {
    "_eventName" = "collection_screen_open";
    "_logTime" = 1545987980;
    "_ui" = "no_ui";
    context = "\U041d\U043e\U0432\U043e\U0433\U043e\U0434\U043d\U0438\U0435 \U043f\U0435\U0441\U043d\U0438 2019";
    "tracks_count" = 50;
}

FBSDKLog: Failed to send AppEvents: Error Domain=com.facebook.sdk.core Code=8 "(null)" UserInfo={com.facebook.sdk:FBSDKGraphRequestErrorCategoryKey=0, com.facebook.sdk:FBSDKGraphRequestErrorHTTPStatusCodeKey=400, com.facebook.sdk:FBSDKErrorDeveloperMessageKey=(#100) This field must be at most 100 characters long., com.facebook.sdk:FBSDKGraphRequestErrorGraphErrorCode=100, com.facebook.sdk:FBSDKGraphRequestErrorParsedJSONResponseKey={
    body =     {
        error =         {
            code = 100;
            "fbtrace_id" = FhXVzSupeRT;
            message = "(#100) This field must be at most 100 characters long.";
            type = OAuthException;
        };
    };
    code = 400;
}}
2018-12-28 11:06:24.060848+0200 AppName[2611:435661] FBSDKLog: FBSDKAppEvents: Flushed @ 1545987982, 2 events due to 'Timer' - {
    "advertiser_id" = "3C8B59FB-6F05-4FB9-8C74-E2AE7C8918CF";
    "advertiser_tracking_enabled" = 1;
    "anon_id" = "XZF9DA16E3-7660-407D-8F9B-931AFC95D2F4";
    "app_user_id" = a839d509bf4389b7a043d89fb0783d3bc3bd68413271994165ac7085780f84df4dcfb68192a2fd07ca6aea27c60345219142c90a5bf1592fbd4617bfa8cc1b95;
    "application_tracking_enabled" = 1;
    "custom_events" = "}
Events: [
  {
    "event" : {
      "_eventName" : "collection_screen_open",
      "_logTime" : 1545987980,
      "tracks_count" : "50",
      "context" : "Новогодние песни 2019",
      "_ui" : "no_ui"
    },
    "isImplicit" : false
  }
]
Flush Result : Server Error - Error Domain=com.facebook.sdk.core Code=8 "(null)" UserInfo={com.facebook.sdk:FBSDKGraphRequestErrorCategoryKey=0, com.facebook.sdk:FBSDKGraphRequestErrorHTTPStatusCodeKey=400, com.facebook.sdk:FBSDKErrorDeveloperMessageKey=(#100) This field must be at most 100 characters long., com.facebook.sdk:FBSDKGraphRequestErrorGraphErrorCode=100, com.facebook.sdk:FBSDKGraphRequestErrorParsedJSONResponseKey={
    body =     {
        error =         {
            code = 100;
            "fbtrace_id" = FhXVzSupeRT;
            message = "(#100) This field must be at most 100 characters long.";
            type = OAuthException;
        };
    };
    code = 400;
}}

What im doing wrong?
Thanks!

**Comment by robtimp** [comment]
@SerhiiMatvieiev `app_user_id` can be no more than 100 characters, but this example uses 128.
