### ISSUE TITLE
Feature Request: Use semantic versions with the facebook-objc-sdk dependency

### ISSUE THREAD

**Issue by jamezilla** [facebook/facebook-swift-sdk#315]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-sdk-swift/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

* assured stable interface
* framework doesn't have to get rebuilt unless facebook-swift-sdk has a an actual version change

It's extremely annoying to have the facebook-objc-sdk dependency in the Cartfile set to `master`. Every time someone runs `carthage update` the entire framework is rebuilt against `master` regardless of whether the facebook-swift-sdk version changed. *It takes a long time to build*. Also, how can anyone be sure the underlying interface is stable? This entire SDK is sitting on top of an unversioned pile of bits.

## Expected Results

Cartfile points to a semantically versioned facebook-objc-sdk dependency.

**Comment by lostatseajoshua** [comment]
#316 Sets carthage to use semantic version so it will be stable.
