### ISSUE TITLE
FaceBookShare's completion doesn't trigger via Native App

### ISSUE THREAD

**Issue by houmie** [facebook/facebook-swift-sdk#321]
## Environment

- Xcode Version: `10.1`
- Swift Version: `4.0`
- Installation Platform & Verison: `[Cocoapods]` version `1.5.3`
- FBSDKShareKit `4.40.0`

Hello,

When I bring up the shared dialogue, I get the following screen on iOS. Once I tap on `Share With Your Facebook App`, it doesn't trigger the `shareDialog.completion` at all (see below for code). But if I log in via the forms shown underneath, it works. 

![img_0768](https://user-images.githubusercontent.com/1832933/51765404-8862b480-20cf-11e9-8167-3ca07d0abb71.PNG)

**Code:**
```
            let myContent = LinkShareContent(url: url!, quote: quote)
            let shareDialog = ShareDialog(content: myContent)
            shareDialog.mode = .automatic
            shareDialog.presentingViewController = self
            shareDialog.completion = { result in
                switch result {
                case .success:
                    print("Share: Success")
                case .cancelled:
                    print("Share: Cancel")
                case .failed:
                    print("Share: Fail")
                }
            }
            do {
                try shareDialog.show()
            } catch {
                self.notifyUserOfSharingError()
            }
```

Please kindly advise as I'm entirely stuck on this.
Many Thanks,
Houman

**Comment by houmie** [comment]
To add some more interesting details to this problem:

If I change `.automatic` to `.native` 

 ```shareDialog.mode = .native```

It will throw an error here, which prints `dialogNotAvailable`.

I have the native facebook app installed. So what gives?

```
do {
                try shareDialog.show()
            } catch {
                print(error)
            }
```


let myContent = LinkShareContent(url: url!, quote: quote)
            let shareDialog = ShareDialog(content: myContent)
            shareDialog.mode = .native
            shareDialog.presentingViewController = self
            shareDialog.completion = { result in
                switch result {
                case .success:
                    print("Share: Success")
                case .cancelled:
                    print("Share: Cancel")
                case .failed:
                    print("Share: Fail")
                }
            }
            do {
                try shareDialog.show()
            } catch {
                print(error)
            }

**Comment by codytwinton** [comment]
Version `0.6.0` was just released for Carthage and Cocoapods with support for Xcode 10.2 and Swift 5.0.

Please upgrade to the latest version and let us know if this resolves your issues.

**Comment by houmie** [comment]
So was the issue actually fixed or you are hoping it has gone away? :-)

**Comment by codytwinton** [comment]
@houmie - I believe this was rooted in a problem with weak references to the delegate responsible for calling the completion block.`0.6.0` should resolve this. However, if this issue is still present in the latest version, please don't hesitate to comment here.

**Comment by houmie** [comment]
Thanks @codytwinton 

I can confirm that I still can replicate the exact same issue with 
```
Installing FBSDKCoreKit 4.44.1
Installing FBSDKShareKit 4.44.1
Installing FacebookCore 0.6.0
Installing FacebookSDK 4.44.1
Installing FacebookShare 0.6.1
```

I haven't been quite able to upgrade to version 5.0.0 due to lack of documentation on how sharing works. Version 5.0.0 is introducing breaking changes as many classes have been renamed.  I don't think this problem is resolved by itself by just upgrading to version 5.0.0 either.

Would you like to reopen this bug, please?

**Comment by codytwinton** [comment]
@houmie - `v5.0` of the ObjC SDK introduced many bug fixes as well. Please upgrade to that version of the SDK.

If you're having issues with the ObjC SDK, please feel free to [file a bug](https://developers.facebook.com/support/bugs/)

**Comment by houmie** [comment]
@codytwinton This issue has never gone away.

I have tested it again with the latest.

```
FacebookSDK (5.2.1)
FBSDKShareKit (5.2.1)
```

I'm sure you know better than this. But bugs don't auto-magically go away just because the version has been bumped up. Unless someone explicitly looks into this bug and fixes it.

This is not how bug reporting should be. Please don't close this bug, as it's not helpful. At least allow someone else to look into this.

We are getting more and more many customer complaints about this that they have shared it on facebook, but the app didn't work as expected. This is because the callbacks don't get fired if the native app is used.  This means fewer people share on facebook, which isn't in your interest either.

Thanks

**Comment by AraibKarim** [comment]
I can confirm i am still getting this issue on Xcode 10.2.1 Swift 5.0

The issue should reopen.
