### ISSUE TITLE
App Store Connect Operation Error

### ISSUE THREAD

**Issue by falsevapor** [facebook/facebook-swift-sdk#323]
I'm using Facebook sdk to work with facebook login. Seems to work fine but....
Trying to upload/validate app to app store it fails validation. I'm getting this error:
"App Store Connect Operation Error"
"No suitable application records were found. Verify your bundle identifier 'org.cocoapods.FacebookLogin' is correct."

I don't understand. My app bundle is of course not 'org.cocoapods.FacebookLogin'.
What am I doing wrong?
 Please help. Need to release the app asap.

**Comment by robtimp** [comment]
@falsevapor Appears this is not related to the Facebook SDK, but either Cocoapods or iTunes Connect.

There's a couple possible fixes here: https://github.com/Alamofire/Alamofire/issues/2020
