### ISSUE TITLE
Preview mode for user profile

### ISSUE THREAD

**Issue by artemkalinovsky** [facebook/facebook-swift-sdk#329]
Hi,

I have user profile link and open it with  `UIApplication.shared.open(facebookAccountUrl, options: [:])`, where **facebookAccountUrl** is `https://www.facebook.com/app_scoped_user_id/YXNpZADpBWEVZAWlhPLTh3UDY2S0pYdTR0LWRkMkwwUnVab0hadzl0YUJiWHNtNm11T0dvendncEdQa1ZAHTWFMdS1nT3p3Vk41RHh5cWljUm9jZAWQxVkx6MTZATUFlZAVmxRMDVxQ0FkeXBSWl9TTldoVXFHVktK/` and when I'm trying to do it for the first time, I always see login page in Safari ![18 02 2019 15 12 13](https://user-images.githubusercontent.com/3019113/52953543-743d6a80-3390-11e9-97ed-59cd9abd7562.png) for public and private profiles. 

How I could open public user profile page in preview mode without asking user for login?

**Comment by robtimp** [comment]
It is no longer possible to get a Facebook profile page from an app-scoped user ID.

See: https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/
