### ISSUE TITLE
Conflict with pod 'MHVideoPhotoGallery', '2.1.3'

### ISSUE THREAD

**Issue by objectisliper** [facebook/facebook-swift-sdk#331]
I have pod 'MHVideoPhotoGallery', '2.1.3' at my project, and when i try to use facebook sdk login (even just simple button from docs) I get error 
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SFAuthenticationViewController viewControllers]: unrecognized selector sent to instance 0x7fc9d6029200'
```
As I saw with exception breakpoint, it causes by 
```
UINavigationController *nav = (UINavigationController*)presented;
```
string at MHVideoPhotoGallery. Is there a way, to obtain this issues, without deleting MHVideoPhotoGallery? There is a problem, that presented has type SFAuthenticationViewController, not 
UINavigationController .

**Comment by codytwinton** [comment]
This doesn't appear to be an issue with the SDK.

Could you provide sample code to help us triage?

**Comment by robtimp** [comment]
@objectisliper Definitely outside the scope of the FBSDK. I believe the issue is here: https://github.com/mariohahn/MHVideoPhotoGallery/blob/261c95f153fd3eb6378a29dd190cdb1b58e01377/MHVideoPhotoGallery/MMHVideoPhotoGallery/MHGalleryController/MHGalleryController.m#L174
