### ISSUE TITLE
Could not build Objective-C module 'FBAudienceNetwork'

### ISSUE THREAD

**Issue by scutletbutt** [facebook/facebook-swift-sdk#362]
On cocoapod
use_modular_headers!
pod ‘FBSDKLoginKit’
pod ‘others stuff’
pod ‘FBAudienceNetwork’ , installation completed 

Everything work fine on simulator until I try to build the app on device(iPad Air 2 ios 12.0.1)
Now can’t build on both simulator and device because 
 
import FBAudienceneNetwork
error message when Xcode build:  “ could not build Objective-C module 'FBAudienceNetwork' “

Any help is appreciated

**Comment by robtimp** [comment]
Be sure to include `use_frameworks!` for Swift.

We’re only able to assist with issues from this Facebook Swift SDK here (FacebookCore, FacebookLogin, FacebookShare). If you’re still experiencing the issue, please contact Facebook developer support here: https://developers.facebook.com/support
