### ISSUE TITLE
facebook completion handler calling when app enters background and foreground

### ISSUE THREAD

**Issue by kunusiths** [facebook/facebook-swift-sdk#367]
FBSDKLoginManager().logIn(withReadPermissions: ["email","public_profile"], from: viewcontroller) { (result, err) in
            if err != nil {
                print("Custom FB Login failed:", err ?? "Data Missing")
                self.snsResponseDelegate?.onSocialFailure(response: err!)
                return
            }

in this above code after opening facebook page if app goes background and again comes foreground
this completion handler is called and facebook app is closed does not retain state when app is relaunched.plz help

**Comment by robtimp** [comment]
@kunusiths This issue was fixed recently, but you may need to update.

If you’re using Cocoapods, run `pod update`. Make sure your `podfile.lock` shows `4.40.0` or newer for `FBSDKCoreKit` and `FBSDKLoginKit`.
