### ISSUE TITLE
FBSDKMath.h file not found

### ISSUE THREAD

**Issue by LoileeBooz** [facebook/facebook-swift-sdk#368]
Build error when performing carthage update.
FBSDKUIUtility.h:21:9: fatal error: ‘FBSDKMath.h’ file not found

It was reverted already 3 days ago after v4.41.0 was released.
https://github.com/facebook/facebook-objc-sdk/pull/958

When can we expect the new release with the fix?

## Environment
- Xcode Version: 10.1
- Swift Version: 4.2
- Installation Platform & Verison: Carthage version 0.32.0

**Comment by robtimp** [comment]
@LoileeBooz Fixed in v4.41.2: https://github.com/facebook/facebook-objc-sdk/releases
