### ISSUE TITLE
Swift 5. Facebook sdk. Pointer is missing a nullability type specifier 

### ISSUE THREAD

**Issue by bermanapps** [facebook/facebook-swift-sdk#383]
I get the following warning in xcode. I've updated the pods, and using swift 5.
Why am I getting this warning?

![Screenshot 2019-03-28 at 21 04 41](https://user-images.githubusercontent.com/28511238/55188133-4f17f500-51a3-11e9-9431-501a87d2fcde.png)

**Comment by bermanapps** [comment]
![Screenshot 2019-03-28 at 21 04 41](https://user-images.githubusercontent.com/28511238/55188090-37d90780-51a3-11e9-96b5-9239feaf0921.png)

**Comment by codytwinton** [comment]
We're in process of submitting a resolution of this on the ObjC SDK side.

**Comment by codytwinton** [comment]
Version `0.6.0` was just released for Carthage and Cocoapods with support for Xcode 10.2 and Swift 5.0.
