### ISSUE TITLE
Linking a static library that was built with -gmodules, but the module cache was not found

### ISSUE THREAD

**Issue by lucianboboc** [facebook/facebook-swift-sdk#404]
I have added the `FacebookSDK` pod which installs `FacebookSDK` and `FBSDKMarketingKit`.
I get a `GenerateDSYMFile` warning:
```FBSDKCoreKit-28FF1ITFGX9G5.pcm
warning: /var/folders/qj/lk4bdr_x5fs9cvcj4jgx61mmy6f8jd/C/org.llvm.clang.codytwinton/ModuleCache/1IDVK6QLUONUT/Darwin-OIGDM4OW9IL3.pcm: 
No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found. 
Redistributable static libraries should never be built with module debugging enabled.
The debug experience will be degraded due to incomplete debug information.
```
I also tried to have this setting in the Podfile but it didn't help:
`config.build_settings['CLANG_ENABLE_MODULE_DEBUGGING'] = 'NO'`

The only fix is to set the `DEBUG_INFORMATION_FORMAT` to `DWARF` instead of `DWARF with dSYM File` or to remove the `FacebookSDK` pod.

A similar issue with the same error messages i've seen here: https://github.com/mobfox/MobFox-iOS-SDK/issues/45

Any help will be appreciated on how to fix this or a pod upgrade is required.

**Comment by lucianboboc** [comment]
It seems if the `FBSDKMarketingKit` is removed the errors will dissapear.

**Comment by joesus** [comment]
@lucianboboc are you still seeing this issue? I tried to reproduce but did not see. Perhaps it was fixed in a previous release?

**Comment by joesus** [comment]
Please migrate to the [other repository](https://github.com/facebook/facebook-ios-sdk). This repository will be archived tomorrow and no longer maintained. #540
If this is still an issue after migrating, please open an issue or file a bug ticket so that we can address the issue.
