### ISSUE TITLE
Facebook Analytics Events Do Not Work With App Extensions?

### ISSUE THREAD

**Issue by TyrantBoy** [facebook/facebook-swift-sdk#428]
Facebook SDK does not log App Events from app extension. I tried to add analytics to the Messages Extension, but nothing returns.

**Comment by joesus** [comment]
Please migrate to the [other repository](https://github.com/facebook/facebook-ios-sdk). This repository will be archived tomorrow and no longer maintained. #540
If this is still an issue after migrating, please open an issue or file a bug ticket so that we can address the issue.
