### ISSUE TITLE
ShareDialog has gone missing in version 5.0.0 

### ISSUE THREAD

**Issue by houmie** [facebook/facebook-swift-sdk#438]
Using FBSDKCoreKit (5.0.0)
Using FBSDKMarketingKit (5.0.0)
Using FBSDKShareKit (5.0.0)
Using FacebookCore (0.7.0)
Using FacebookSDK (5.0.0)
Using FacebookShare (0.7.0)

Both `LinkShareContent` and `ShareDialog` are completely gone. 

```
let myContent = LinkShareContent(url: url!, quote: quote)
let shareDialog = ShareDialog(content: myContent)
```

There seem to be no documentation about this either.

Thanks

**Comment by jilouc** [comment]
Seems like it's now possible to just use FBSDKShareKit for that.  
`import FBSDKShareKit` and replacing `LinkShareContent` with `ShareLinkContent` works.

**Comment by houmie** [comment]
Thank you for that.  How about the delegate?
We used to have a completion handler like this.

```
shareDialog.completion = { result in
                switch result {
                case .success:
                      print("Share: Success")
                case .cancelled:
                      print("Share: Cancel")
                case .failed:
                      print("Share: Fail")
                }
}```

**Comment by vimask** [comment]
```
let content = ShareLinkContent()
content.contentURL = URL(string: url)!
ShareDialog(fromViewController: self, content: content, delegate: self).show()
```
the delegate like this:
```
//MARK: - FACEBOOK SHARE DELEGATE
extension YourCurrentViewController: SharingDelegate {
    func sharer(_ sharer: Sharing, didCompleteWithResults results: [String : Any]) {
        if sharer.shareContent.pageID != nil {
            showSimpleAlert("", message: "Your video story has been shared.", presentingController: self)
        }

    }
    
    func sharer(_ sharer: Sharing, didFailWithError error: Error) {
        showSimpleAlert(Strings.error, message: "Failed. Try again.", presentingController: self)
    }
    
    func sharerDidCancel(_ sharer: Sharing) {}
}
```

**Comment by houmie** [comment]
@vimask Thank you that worked perfectly.   I now removed ```pod FacebookShare``` altogether as I don't need it anymore.

Was FacebookShare supposed to be a wrapper on top of FBSDKShareKit to make it easier?

**Comment by joesus** [comment]
@houmie. In short. Yes. The idea was (and still is) to have the Swift SDK exist as a wrapper to bring modern iOS concepts into Swift. There PR  #509 adds back typealiases as a starting point for removing the need to import FBSDK-prefixed dependencies. This will be in the next minor release. Closing.
