### ISSUE TITLE
Issue with sharing photo with metadata iOS SDK.

### ISSUE THREAD

**Issue by Alhantro** [facebook/facebook-swift-sdk#445]
We have found an issue with the facebook sharing SDK for iOS. When we are sharing the image with the metadata of 360 equirectangular panorama the it looks like a usual photo in post. But image with the same metadata loads as panorama if we uploading it from the PC.  Photo which posted to facebook has less resolution and cleaned metadata. Also it has different sizes. (277 Kb - original, 31 Kb - photo from facebook).

`let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first! + "/"
let filePath = path + name + "fb" + ".jpg"

let testpath = Bundle.main.url(forResource: "keks", withExtension: "jpg") // image with metadata

            let dataTestOne = try? Data(contentsOf: testpath!)
            
            fileManager.createFile(atPath: filePath, contents: dataTestOne, attributes: [kCFURLFileProtectionKey as FileAttributeKey: kCFURLFileProtectionComplete]) 
            
            try? PHPhotoLibrary.shared().performChangesAndWait {
                PHAssetChangeRequest.creationRequestForAssetFromImage(atFileURL: URL(fileURLWithPath: filePath))
            }
            
            let options = PHFetchOptions()
            options.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: true)]
            let assets: PHFetchResult<PHAsset> = PHAsset.fetchAssets(with: options)
            var lastAsset: PHAsset?
            if assets.count > 0 {
                lastAsset = assets.lastObject     // This photo in gallery still has metadata
            }
            
            
            let photo = FBSDKSharePhoto(photoAsset: lastAsset, userGenerated: true)
            let content = FBSDKSharePhotoContent()
            content.photos = [photo]
        
            let dialog = FBSDKShareDialog()
            dialog.fromViewController = self
            dialog.shareContent = content
            dialog.mode = FBSDKShareDialogMode.automatic
            dialog.show()`

**Comment by joesus** [comment]
@Alhantro, I have a suspicion this may be intentional but are you able to provide a link to a sample project reproducing the issue?

**Comment by joesus** [comment]
Please migrate to the [other repository](https://github.com/facebook/facebook-ios-sdk). This repository will be archived tomorrow and no longer maintained. #540
If this is still an issue after migrating, please open an issue or file a bug ticket so that we can address the issue.
