### ISSUE TITLE
Feature Request: Future of this SDK

### ISSUE THREAD

**Issue by dimitris-c** [facebook/facebook-swift-sdk#447]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-swift-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

The future of this sdk...

## Expected Results

What do you expect to happen with this SDK from now on?

Much of the code has been removed from this SDK in the last Release, I understand this is in Beta but previously there were a ton of useful stuff that required almost no importing of the Obj-C SDK. So what's the roadmap for this SDK... 
(Plenty of bug issues are open at the moment due to the latest release)

**Comment by iosdevben** [comment]
https://github.com/facebook/facebook-swift-sdk/blob/master/ROADMAP.md

**Comment by dimitris-c** [comment]
Thanks 👍
