### ISSUE TITLE
ShareLinkContent is GONE

### ISSUE THREAD

**Issue by greatsk55** [facebook/facebook-swift-sdk#450]
## Checklist

- [
Installing FBSDKCoreKit (was 5.0.0)
Installing FBSDKLoginKit (was 5.0.0)
Installing FBSDKShareKit (was 5.0.0)
Installing FacebookCore (was 0.7.0)
Installing FacebookLogin (was 0.7.0)
Installing FacebookShare (was 0.7.0) 
] 
I've updated to the latest released version of the SDK

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `10.2.1`
- Swift Version: `5.0.0`
- Installation Platform & Verison: `[Cocoapods|Carthage|Manual]` version `X.X.X`

## Goals

LinkShareContent is undefined error!

What do you want to achieve?

## Expected Results

What do you expect to happen?

I want to share it on Facebook

## Actual Results

cannot build

What actually happened? Can you provide a stack trace?

## Steps to Reproduce

What are the steps necessary to reproduce this issue?

## Code Samples & Details

Please provide a code sample, as well as any additional details, to help us track down the issue. If you can provide a link to a test project that allows us to reproduce the issue, this helps us immensely in both the speed and quality of the fix.

**Note:** Remember to format your code for readability:

```swift
var content:LinkShareContent = LinkShareContent.init(url: URL.init(string: "\(Server.baseURL)/link)") ?? URL.init(fileURLWithPath: "\(Server.baseURL)/link"), quote: "HI")

        let shareDialog = ShareDialog(content: "\(Server.baseURL)/link")
        content.hashtag = Hashtag("myApp")
        shareDialog.mode = .native
        shareDialog.failsOnInvalidData = true
        shareDialog.completion = { result in
            // Handle share results
        }
        do{
            try shareDialog.show()
        }
        catch{
            gotoURL("https://www.facebook.com/sharer/sharer.php?s=100&p[url]=\(Server.baseURL)/link")
        }

```

**Comment by piotrros** [comment]
+1

**Comment by joesus** [comment]
This has the same cause as #433. The closing reason on that task links to a changelog that should help resolve your issue.
