### ISSUE TITLE
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by devny** [facebook/facebook-swift-sdk#452]
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

Error Required

FBSDKAppEvents.m file.
    UIViewController *vc = [UIApplication sharedApplication].keyWindow.rootViewController;  
      applicationState = [UIApplication sharedApplication].applicationState; 

line!!

**Comment by devny** [comment]
Success Build

**Comment by omarDtp** [comment]
useless issue
