### ISSUE TITLE
Carthage + Xcode 11 beta failed to compile the framework

### ISSUE THREAD

**Issue by Bosian** [facebook/facebook-swift-sdk#468]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.0`
- Swift Version: `5.1`
- Installation Platform & Verison: `[Carthage]` version `master`

![螢幕快照 2019-06-13 下午2 41 47](https://user-images.githubusercontent.com/9071512/59409944-14107f80-8dea-11e9-98e3-44b63b109a2e.png)

**Comment by justinHuangNoodoe** [comment]
same problem

**Comment by paulBuchanan** [comment]
I have the same issue.

**Comment by rushilshah** [comment]
Same issue. It has some issue with `FacebookShare` schema when I tried to build the project in Xcode 11.

**Comment by CodeStage** [comment]
Yes, the strange thing is that the Frameworks can be built by opening Xcode, but not via the CLI calls Carthage makes

**Comment by CodeStage** [comment]
This startet with Beta 4, everything was fine with the other beta versions of Xcode 11

**Comment by rushilshah** [comment]
@nafu Thank you so much.
