### ISSUE TITLE
Typedef redefinition with different types ('NSInteger' (aka 'long') vs 'enum ACAccountCredentialRenewResult')

### ISSUE THREAD

**Issue by bhanuteja501** [facebook/facebook-swift-sdk#473]
I just updated 'FacebookLogin' pod. And when i tried to run am getting
Typedef redefinition with different types ('NSInteger' (aka 'long') vs 'enum ACAccountCredentialRenewResult')
error in FBSDKLoiginManaher.h file

![65491131_345702772781308_254756925760077824_n](https://user-images.githubusercontent.com/42807037/60102014-7ec2a300-977a-11e9-9fa1-ec1dd790b65f.png)

**Comment by joesus** [comment]
The Swift SDK is still in beta. I would advise using the ObjC version of the SDK to get unblocked while we look into this.
