### ISSUE TITLE
Feature Request: Support for Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by oscarvgg** [facebook/facebook-swift-sdk#491]
Goals:

Add the facebook SDK to a project using SPM.

**Comment by gabrielPeart** [comment]
Super necessary

**Comment by joesus** [comment]
This feature request doesn't appear to be actively being worked on. We would happily consider a pull request implementing it. If you plan to work on this issue let us know in the comments and we will re-open the issue and assign it to you. If you feel strongly that this issue deserves more attention, please comment here with your use-case and we will try to prioritize as appropriate.

**Comment by joona0825** [comment]
@joesus Hi. I would like to make this project SPM compatibly. Is there anything I should know before do the work?

**Comment by davidrothera** [comment]
I wouldn’t think so. We don’t have full tests yet so please just test that both methods of integration still work.

**Comment by joesus** [comment]
There's an open pr that adds some tests but they are in a directory named "Tests" side by side with "Sources" so that should should be super easy to fit in during or after the SPM work. Thank you so much @joona0825!!! 🎉

**Comment by ethanwa** [comment]
I would love to see this!

**Comment by joona0825** [comment]
I tried to make this repo SPM compatibly, but I have encountered a large number of ".h file not found" errors, and to resolve it I need to modify Objective-C libraries. I tried to fix them too, but I could not figure out what the actual problem is. I think I'll need much more time to make this available

**Comment by joesus** [comment]
This is now available on the master branch of https://github.com/facebook/facebook-ios-sdk and should be in the next release. 🥂

Also. Please migrate to the other repository. This repository will be archived tomorrow and no longer maintained. #540
