### ISSUE TITLE
Bug: ITMS-90809: Deprecated API Usage - UIWebView #519

### ISSUE THREAD

**Issue by peterkuch** [facebook/facebook-swift-sdk#524]
Bug: ITMS-90809: Deprecated API Usage - UIWebView #519, app store not approved. Hope facebook new release as soon as possible.

**Comment by joesus** [comment]
Please use v0.9.0. It has the updates from ObjC SDK.

**Comment by peterkuch** [comment]
@joesus Thanks you so much for feedback , now, i success got it and nice to fast update. :)
