### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by tanand7** [facebook/facebook-swift-sdk#526]
Got following mail from Apple after submitting the building

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

When I searched inside the project I found that UIWebView is used in FBSDKWebDialogView class. So they should be replaced with WKWebView

**Comment by krishnaSoni2113** [comment]
@tanand7 
It is fixed in new release, Update your pod if you are using it or else use latest SDK. Thanks

**Comment by joesus** [comment]
Released in v0.9.0
