### ISSUE TITLE
No SDKs found for scheme

### ISSUE THREAD

**Issue by bukira** [facebook/facebook-swift-sdk#531]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.0`
- Swift Version: `5.1`
- Installation Platform & Verison: `Carthage|` version `033.0`

## Goals

Builds the scheme

## Expected Results

Builds

## Actual Results

*** Building scheme "KBaseLiteWatch" in KBase.xcodeproj

Fatal error: No SDKs found for scheme KBaseLiteWatch: file /Users/vagrant/git/Source/CarthageKit/Xcode.swift, line 600

## Steps to Reproduce

This used to build previously, using the same version of Carthage but swift 5.0 and Xcode 10

My other schemes all build, not sure what it means by no SDKs?

**Comment by joesus** [comment]
This seems like it is likely a separate issue. There is no constant KBaseLiteWatch in the SDK. Closing.

**Comment by bukira** [comment]
Sorry I think this got posted to the wrong GitHub project , it was meant for the Carthage project not this, sorry
